import express, { Request, Response } from "express"
import cors from "cors"
import path from "path"
import helmet from "helmet"
import fileUpload from "express-fileupload"

import { DB_HOST, DB_NAME, DB_USER, FRONTEND_URL, NODE_ENV } from "@/config"
import { requestLoggerMiddleware } from "@/middleware"
import logger from "@/utils/logger"
import router from "@/routes"

const app = express()

app.use(requestLoggerMiddleware)
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      "default-src": ["'self'", "https://dev-0tc6bn14.eu.auth0.com"],
      "base-uri": ["'self'"],
      "block-all-mixed-content": [],
      "font-src": ["'self'", "https:", "data:"],
      "frame-ancestors": ["'self'"],
      "img-src": ["'self'", "data:", "https:"],
      "object-src": ["'none'"],
      "script-src": ["'self'", "https://js.arcgis.com", "'unsafe-eval'"], // added https to accomodate esri components?
      "script-src-attr": ["'none'"],
      "style-src": ["'self'", "https:", "'unsafe-inline'"],
      "worker-src": ["'self'", "blob:"],
      "connect-src": ["'self'", "https://dev-0tc6bn14.eu.auth0.com"],
    },
  })
)
app.use(
  cors({
    origin: FRONTEND_URL,
    optionsSuccessStatus: 200,
    credentials: true,
    exposedHeaders: "Content-Disposition",
  })
)

// for parsing application/json
app.use(express.json())
// for parsing application/x-www-form-urlencoded
app.use(
  express.urlencoded({
    extended: true,
  })
)
// Adds FormData support
app.use(fileUpload())

if (NODE_ENV !== "test") {
  logger.info(`host: ${DB_HOST}`)
  logger.info(`user: ${DB_USER}`)
  logger.info("psss: *********")
  logger.info(`db name: ${DB_NAME}`)
}

app.use(router)

// serves the static files generated by the front-end
app.use(express.static(path.join(__dirname, "web")))

// if no other routes match, just send the front-end
app.use((_req: Request, res: Response) => {
  res.sendFile(path.join(__dirname, "web") + "/index.html")
})

export default app
