import * as knex from 'knex';

// CREATE TABLE Travel.destination (
// 	DestinationID smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
// 	province varchar(5) NOT NULL,
// 	city varchar(50) NOT NULL
// );

exports.up = function (knex: knex.Knex, Promise: any) {
	return knex.schema.createTable('destinations', function (t) {
		t.increments('id').notNullable().primary();
		t.string('province').notNullable();
		t.string('city').notNullable();
	});
};

exports.down = function (knex: knex.Knex, Promise: any) {
	return knex.schema.dropTable('destinations');
};
