import * as knex from 'knex';

// create Table Travel.Expense(
// 	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
// 	taid smallint, --fk
// 	expensetype varchar(15),
// 	expensedesc varchar(100),
// 	quantity smallint,
// 	amount smallint,
// 	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
// );

exports.up = function (knex: knex.Knex, Promise: any) {
	return knex.schema.createTable('expenses', function (t) {
		t.increments('id').notNullable().primary();
		t.integer('taid').notNullable();
		t.string('type').notNullable();
		t.string('description').notNullable();
		t.date('date').notNullable();
		t.integer('cost').notNullable();
		t.string('currency').notNullable();
	});
};

exports.down = function (knex: knex.Knex, Promise: any) {
	return knex.schema.dropTable('expenses');
};
