import * as knex from 'knex';

// create table Travel.Stops(
// 	id smallint GENERATED BY DEFAULT AS IDENTITY primary key,
// 	taid smallint, --fk
// 	travelFrom varchar(100),
// 	travelTo varchar(100),
// 	departureDate date,
// 	departureTime time,
// 	transport varchar(100),
// 	estimate smallint,
// 	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
// );

exports.up = function (knex: knex.Knex, Promise: any) {
	return knex.schema.createTable('stops', function (t) {
		t.increments('id').notNullable().primary();
		t.integer('taid').notNullable();
		t.string('travelFrom');
		t.string('travelTo');
		t.date('departureDate');
		t.time('departureTime');
		t.string('transport');
		t.integer('estimate');
	});
};

exports.down = function (knex: knex.Knex, Promise: any) {
	return knex.schema.dropTable('stops');
};
