drop table IF EXISTS Travel.Docs;
drop table IF EXISTS Travel.RecieptBackup;
drop Table IF EXISTS Travel.Expense;
drop table IF EXISTS Travel.Advance;
drop table IF EXISTS Travel.CostEstimate;
drop table IF EXISTS Travel.Carryout;
drop table IF EXISTS Travel.Approve;
drop table IF EXISTS Travel.FlightRequest;
drop table IF EXISTS Travel.Stops;
drop table IF EXISTS Travel.Auth;
drop table IF EXISTS Travel.PreAppDoc;
drop table IF EXISTS Travel.PreAppEmployee;
drop Table IF EXISTS Travel.PreApprove;
drop Table IF EXISTS Travel.Purpose;
drop table IF EXISTS Travel.FlightEstimateLookup;
drop table IF EXISTS Travel.RentalCarLookup;
drop table IF EXISTS Travel.PoolCarLookup;
drop table IF EXISTS Travel.PurposeLookup;
drop table IF EXISTS Travel.destination;
drop table IF EXISTS Travel.roles;
drop table IF EXISTS Travel.roleAssignments;
drop table IF EXISTS Travel.departments;
drop table IF EXISTS Travel.departmentAssignments;
drop table IF EXISTS Travel.user;

---CREATE TABLES
CREATE TABLE Travel.user (
	id smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	email varchar(200) NOT NULL,
	is_active bit NOT NULL DEFAULT ('1'),
	first_name varchar(100) NOT NULL,
	last_name varchar(100) NOT NULL,
	create_date timestamp NOT NULL DEFAULT (NOW())
);

INSERT INTO travel."user" (id, email, is_active, first_name, last_name, create_date) VALUES
(1, 'Max.parker@yukon.ca', '1', 'Max', 'parker', '2022-03-25 15:09:10.391');

CREATE TABLE Travel.roles (
	id smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	roleName varchar(32) NOT NULL
);

INSERT INTO travel."roles" (id, roleName) VALUES (1, 'Admin');
INSERT INTO travel."roles" (id, roleName) VALUES (2, 'Supervisor');
INSERT INTO travel."roles" (id, roleName) VALUES (3, 'User');

CREATE TABLE Travel.roleAssignments (
	id smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	userId smallint NOT NULL,
	roleId smallint NOT NULL
);

INSERT INTO travel."roleassignments" (id, userId, roleId) VALUES
(1, 1, 1);


CREATE TABLE Travel.departments (
	id smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	name varchar(250) NOT NULL,
	type varchar (64) NOT NULL,
	ownedBy smallint not null
);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (1, 'Community Services', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (2, 'Economic Development', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (3, 'Education', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (4, 'Energy, Mines and Resources', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (5, 'Environment', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (6, 'Executive Council Office', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (7, 'Finance', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (8, 'French Language Services Directorate', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (9, 'Health and Social Services', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (10, 'Highways and Public Works', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (11, 'Justice', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (12, 'Public Service Commission', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (13, 'Tourism and Culture', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (14, 'Women Gender Equity Directorate', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (15, 'Corporations', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (16, 'Yukon Energy Corporation', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (17, 'Yukon Development Corporation', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (18, 'Yukon Housing Corporation', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (19, 'Yukon Liquor Corporation', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (20, 'Yukon Lottery Commission and Lotteries Yukon', 'department', 0);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (21, 'Yukon Workers'' Compensation Health and Safety Board', 'department', 0);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (22, 'Building Safety', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (23, 'Community Affairs', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (24, 'Community Operations', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (25, 'Corporate Affairs', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (26, 'Emergency Measures Organization', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (27, 'Emergency Medical Services', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (28, 'Employment Standards', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (29, 'Fire Marshal''s Office', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (30, 'Infrastructure Development', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (31, 'Land Development', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (32, 'Professional Licensing and Regulatory Affairs', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (33, 'Property Assessment and Taxation', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (34, 'Residential Tenancies Office', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (35, 'Sport and Recreation', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (36, 'Wildland Fire Management', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (37, 'Yukon Public Libraries', 'branch', 1);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (38, 'Organizational structure', 'branch', 1);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (39, 'Community Development Fund (CDF)', 'branch', 2);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (40, 'Economic Development Fund', 'branch', 2);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (41, 'Immigration', 'branch', 2);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (42, 'Media Development', 'branch', 2);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (43, 'Apprenticeship Training', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (44, 'Communications', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (45, 'Curriculum and Assessment', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (46, 'Deputy Minister''s Office', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (47, 'Early Learning and Child Care', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (48, 'First Nations Initiatives', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (49, 'French Programs', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (50, 'Human Resources', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (51, 'Post-Secondary and Labour Market', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (52, 'Schools and Student Services', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (53, 'Student Financial Assistance', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (54, 'Student Support Services', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (55, 'Student Training and Employment Program (STEP)', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (56, 'Student Transportation', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (57, 'Teacher Certification', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (58, 'Teaching Employment', 'branch', 3);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (59, 'Organizational structure', 'branch', 3);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (60, 'Agriculture', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (61, 'Assessment and Abandoned Mines', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (62, 'Communications', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (63, 'Compliance Monitoring and Inspections', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (64, 'Energy', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (65, 'Energy, Mines and Resources Library', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (66, 'Forest Management', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (67, 'Land Management', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (68, 'Land Planning', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (69, 'Mineral Resources', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (70, 'Oil and Gas Resources', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (71, 'Strategic Alliances', 'branch', 4);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (72, 'Yukon Geological Survey', 'branch', 4);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (73, 'Client Solutions', 'branch', 5);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (74, 'Animal Health Unit', 'branch', 5);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (75, 'Climate Change Secretariat', 'branch', 5);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (76, 'Conservation Officer Services', 'branch', 5);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (77, 'Environmental Protection and Assessment', 'branch', 5);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (78, 'Fish and Wildlife', 'branch', 5);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (79, 'Water Resources', 'branch', 5);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (80, 'Yukon Parks', 'branch', 5);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (81, 'Aboriginal Relations', 'branch', 6);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (82, 'Office of the Science Advisor', 'branch', 6);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (83, 'Intergovernmental Relations', 'branch', 6);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (84, 'Youth Directorate', 'branch', 6);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (85, 'Government Internal Audit Services', 'branch', 6);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (86, 'Yukon Water Board', 'branch', 6);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (87, 'Major Projects Yukon', 'branch', 6);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (88, 'General finance enquiries', 'branch', 7);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (89, 'Communications', 'branch', 7);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (90, 'Accounts Payable', 'branch', 7);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (91, 'Accounts Receivable', 'branch', 7);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (92, 'Tax Administration', 'branch', 7);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (93, 'Yukon Bureau of Statistics', 'branch', 7);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (94, 'Reception', 'branch', 8);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (95, 'Communications and policy', 'branch', 8);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (96, 'Finance and planning', 'branch', 8);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (97, 'French Web and social media coordination', 'branch', 8);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (98, 'Language training and assessment', 'branch', 8);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (99, 'Program development', 'branch', 8);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (100, 'Translation', 'branch', 8);

INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (101, 'Corporate Services', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (102, 'Health', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (103, 'Finance', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (104, 'Policy and Program Development', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (105, 'Continuing Care', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (106, 'Program Support', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (107, 'Safety and Clinical Excellence', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (108, 'Quality, Risk and Clinical Practice', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (109, 'Clinical Psychology', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (110, 'Extended Care Services', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (111, 'Care and Community', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (112, 'Aging in Place', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (113, 'Health Services', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (114, 'Insured Health and Hearing Services', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (115, 'Hearing Services', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (116, 'Extended Benefits and Pharmaceutical Programs', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (117, 'Registration, Physician and Hospital Claims, Medical Travel', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (118, 'Vital Statistics', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (119, 'Community Nursing', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (120, 'Clinical Practice and Programs', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (121, 'Chronic Conditions Support Program', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (122, 'Community Health Programs', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (123, 'Yukon Children’s Dental Program', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (124, 'Environmental Health Services', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (125, 'Health Promotion', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (126, 'Yukon Communicable Disease Control', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (127, 'Immunization Program', 'branch', 9);
INSERT INTO travel."departments" (id, name, type, ownedBy) VALUES (128, 'Social Services', 'branch', 9);


CREATE TABLE Travel.departmentAssignments (
	id smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	userId smallint NOT NULL,
	objectId smallint NOT NULL
);

CREATE TABLE Travel.destination (
	DestinationID smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	province varchar(5) NOT NULL,
	city varchar(50) NOT NULL
);

insert into Travel.destination(province, city) values ('AB','Airdrie');
insert into Travel.destination(province, city) values ('AB','Grande Prairie');
insert into Travel.destination(province, city) values ('AB','Red Deer');
insert into Travel.destination(province, city) values ('AB','Beaumont');
insert into Travel.destination(province, city) values ('AB','Hanna');
insert into Travel.destination(province, city) values ('AB','St. Albert');
insert into Travel.destination(province, city) values ('AB','Bonnyville');
insert into Travel.destination(province, city) values ('AB','Hinton');
insert into Travel.destination(province, city) values ('AB','Spruce Grove');
insert into Travel.destination(province, city) values ('AB','Brazeau');
insert into Travel.destination(province, city) values ('AB','Irricana');
insert into Travel.destination(province, city) values ('AB','Strathcona County');
insert into Travel.destination(province, city) values ('AB','Breton');
insert into Travel.destination(province, city) values ('AB','Lacombe');
insert into Travel.destination(province, city) values ('AB','Strathmore');
insert into Travel.destination(province, city) values ('AB','Calgary');
insert into Travel.destination(province, city) values ('AB','Leduc');
insert into Travel.destination(province, city) values ('AB','Sylvan Lake');
insert into Travel.destination(province, city) values ('AB','Camrose');
insert into Travel.destination(province, city) values ('AB','Lethbridge');
insert into Travel.destination(province, city) values ('AB','Swan Hills');
insert into Travel.destination(province, city) values ('AB','Canmore');
insert into Travel.destination(province, city) values ('AB','McLennan');
insert into Travel.destination(province, city) values ('AB','Taber');
insert into Travel.destination(province, city) values ('AB','Didzbury');
insert into Travel.destination(province, city) values ('AB','Medicine Hat');
insert into Travel.destination(province, city) values ('AB','Turner Valley');
insert into Travel.destination(province, city) values ('AB','Drayton Valley');
insert into Travel.destination(province, city) values ('AB','Olds');
insert into Travel.destination(province, city) values ('AB','Vermillion');
insert into Travel.destination(province, city) values ('AB','Edmonton');
insert into Travel.destination(province, city) values ('AB','Onoway');
insert into Travel.destination(province, city) values ('AB','Wood Buffalo');
insert into Travel.destination(province, city) values ('AB','Ft. SK');
insert into Travel.destination(province, city) values ('AB','Provost');
insert into Travel.destination(province, city) values ('BC','Burnaby');
insert into Travel.destination(province, city) values ('BC','Lumby');
insert into Travel.destination(province, city) values ('BC','City of Port Moody');
insert into Travel.destination(province, city) values ('BC','Cache Creek');
insert into Travel.destination(province, city) values ('BC','Maple Ridge');
insert into Travel.destination(province, city) values ('BC','Prince George');
insert into Travel.destination(province, city) values ('BC','Castlegar');
insert into Travel.destination(province, city) values ('BC','Merritt');
insert into Travel.destination(province, city) values ('BC','Prince Rupert');
insert into Travel.destination(province, city) values ('BC','Chemainus');
insert into Travel.destination(province, city) values ('BC','Mission');
insert into Travel.destination(province, city) values ('BC','Richmond');
insert into Travel.destination(province, city) values ('BC','Chilliwack');
insert into Travel.destination(province, city) values ('BC','Nanaimo');
insert into Travel.destination(province, city) values ('BC','Saanich');
insert into Travel.destination(province, city) values ('BC','Clearwater');
insert into Travel.destination(province, city) values ('BC','Nelson');
insert into Travel.destination(province, city) values ('BC','Sooke');
insert into Travel.destination(province, city) values ('BC','Colwood');
insert into Travel.destination(province, city) values ('BC','New Westminster');
insert into Travel.destination(province, city) values ('BC','Sparwood');
insert into Travel.destination(province, city) values ('BC','Coquitlam');
insert into Travel.destination(province, city) values ('BC','North Cowichan');
insert into Travel.destination(province, city) values ('BC','Surrey');
insert into Travel.destination(province, city) values ('BC','Cranbrook');
insert into Travel.destination(province, city) values ('BC','North Vancouver');
insert into Travel.destination(province, city) values ('BC','Terrace');
insert into Travel.destination(province, city) values ('BC','Dawson Creek');
insert into Travel.destination(province, city) values ('BC','North Vancouver');
insert into Travel.destination(province, city) values ('BC','Tumbler');
insert into Travel.destination(province, city) values ('BC','Delta');
insert into Travel.destination(province, city) values ('BC','Osoyoos');
insert into Travel.destination(province, city) values ('BC','Vancouver');
insert into Travel.destination(province, city) values ('BC','Fernie');
insert into Travel.destination(province, city) values ('BC','Parksville');
insert into Travel.destination(province, city) values ('BC','Vancouver');
insert into Travel.destination(province, city) values ('BC','Invermere');
insert into Travel.destination(province, city) values ('BC','Peace River');
insert into Travel.destination(province, city) values ('BC','Vernon');
insert into Travel.destination(province, city) values ('BC','Kamloops');
insert into Travel.destination(province, city) values ('BC','Penticton');
insert into Travel.destination(province, city) values ('BC','Victoria');
insert into Travel.destination(province, city) values ('BC','Kaslo');
insert into Travel.destination(province, city) values ('BC','Port Alberni');
insert into Travel.destination(province, city) values ('BC','Whistler');
insert into Travel.destination(province, city) values ('BC','Langley');
insert into Travel.destination(province, city) values ('BC','Port Hardy');
insert into Travel.destination(province, city) values ('MB','Birtle');
insert into Travel.destination(province, city) values ('MB','Flin Flon');
insert into Travel.destination(province, city) values ('MB','Swan River');
insert into Travel.destination(province, city) values ('MB','Brandon');
insert into Travel.destination(province, city) values ('MB','Snow Lake');
insert into Travel.destination(province, city) values ('MB','The Pas');
insert into Travel.destination(province, city) values ('MB','Cranberry Portage');
insert into Travel.destination(province, city) values ('MB','Steinbach');
insert into Travel.destination(province, city) values ('MB','Thompson');
insert into Travel.destination(province, city) values ('MB','Dauphin');
insert into Travel.destination(province, city) values ('MB','Stonewall');
insert into Travel.destination(province, city) values ('MB','Winnipeg');
insert into Travel.destination(province, city) values ('NB','Cap-Pele');
insert into Travel.destination(province, city) values ('NB','Miramichi');
insert into Travel.destination(province, city) values ('NB','Saint John');
insert into Travel.destination(province, city) values ('NB','Fredericton');
insert into Travel.destination(province, city) values ('NB','Moncton');
insert into Travel.destination(province, city) values ('NB','Saint Stephen');
insert into Travel.destination(province, city) values ('NB','Grand Bay-Westfield');
insert into Travel.destination(province, city) values ('NB','Oromocto');
insert into Travel.destination(province, city) values ('NB','Shippagan');
insert into Travel.destination(province, city) values ('NB','Grand Falls');
insert into Travel.destination(province, city) values ('NB','Port Elgin');
insert into Travel.destination(province, city) values ('NB','Sussex');
insert into Travel.destination(province, city) values ('NB','Memramcook');
insert into Travel.destination(province, city) values ('NB','Sackville');
insert into Travel.destination(province, city) values ('NB','Tracadie-Sheila');
insert into Travel.destination(province, city) values ('NL','Argentia');
insert into Travel.destination(province, city) values ('NL','Corner Brook');
insert into Travel.destination(province, city) values ('NL','Paradise');
insert into Travel.destination(province, city) values ('NL','Bishop''s Falls');
insert into Travel.destination(province, city) values ('NL','Labrador City');
insert into Travel.destination(province, city) values ('NL','Portaux Basques');
insert into Travel.destination(province, city) values ('NL','Botwood');
insert into Travel.destination(province, city) values ('NL','Mount Pearl');
insert into Travel.destination(province, city) values ('NL','St. John''s');
insert into Travel.destination(province, city) values ('NL','Brigus');
insert into Travel.destination(province, city) values ('NT','Town of Hay River');
insert into Travel.destination(province, city) values ('NT','Town of Inuvik');
insert into Travel.destination(province, city) values ('NT','Yellowknife');
insert into Travel.destination(province, city) values ('NS','Amherst');
insert into Travel.destination(province, city) values ('NS','Hants County');
insert into Travel.destination(province, city) values ('NS','Pictou');
insert into Travel.destination(province, city) values ('NS','Annapolis');
insert into Travel.destination(province, city) values ('NS','Inverness County');
insert into Travel.destination(province, city) values ('NS','Pictou County');
insert into Travel.destination(province, city) values ('NS','Argyle');
insert into Travel.destination(province, city) values ('NS','Kentville');
insert into Travel.destination(province, city) values ('NS','Queens');
insert into Travel.destination(province, city) values ('NS','Baddeck');
insert into Travel.destination(province, city) values ('NS','County of Kings');
insert into Travel.destination(province, city) values ('NS','Richmond');
insert into Travel.destination(province, city) values ('NS','Bridgewater');
insert into Travel.destination(province, city) values ('NS','Lunenburg');
insert into Travel.destination(province, city) values ('NS','Shelburne');
insert into Travel.destination(province, city) values ('NS','Cape Breton');
insert into Travel.destination(province, city) values ('NS','Lunenburg County');
insert into Travel.destination(province, city) values ('NS','Stellarton');
insert into Travel.destination(province, city) values ('NS','Chester');
insert into Travel.destination(province, city) values ('NS','Mahone Bay');
insert into Travel.destination(province, city) values ('NS','Truro');
insert into Travel.destination(province, city) values ('NS','Cumberland County');
insert into Travel.destination(province, city) values ('NS','New Glasgow');
insert into Travel.destination(province, city) values ('NS','Windsor');
insert into Travel.destination(province, city) values ('NS','East Hants');
insert into Travel.destination(province, city) values ('NS','New Minas');
insert into Travel.destination(province, city) values ('NS','Yarmouth');
insert into Travel.destination(province, city) values ('NS','Halifax');
insert into Travel.destination(province, city) values ('NS','Parrsboro');
insert into Travel.destination(province, city) values ('ON','Ajax');
insert into Travel.destination(province, city) values ('ON','Halton');
insert into Travel.destination(province, city) values ('ON','Peterborough');
insert into Travel.destination(province, city) values ('ON','Atikokan');
insert into Travel.destination(province, city) values ('ON','Halton Hills');
insert into Travel.destination(province, city) values ('ON','Pickering');
insert into Travel.destination(province, city) values ('ON','Barrie');
insert into Travel.destination(province, city) values ('ON','Hamilton');
insert into Travel.destination(province, city) values ('ON','Port Bruce');
insert into Travel.destination(province, city) values ('ON','Belleville');
insert into Travel.destination(province, city) values ('ON','Hamilton-Wentworth');
insert into Travel.destination(province, city) values ('ON','Port Burwell');
insert into Travel.destination(province, city) values ('ON','Blandford-Blenheim');
insert into Travel.destination(province, city) values ('ON','Hearst');
insert into Travel.destination(province, city) values ('ON','Port Colborne');
insert into Travel.destination(province, city) values ('ON','Blind River');
insert into Travel.destination(province, city) values ('ON','Huntsville');
insert into Travel.destination(province, city) values ('ON','Port Hope');
insert into Travel.destination(province, city) values ('ON','Brampton');
insert into Travel.destination(province, city) values ('ON','Ingersoll');
insert into Travel.destination(province, city) values ('ON','Prince Edward');
insert into Travel.destination(province, city) values ('ON','Brant');
insert into Travel.destination(province, city) values ('ON','James');
insert into Travel.destination(province, city) values ('ON','Quinte West');
insert into Travel.destination(province, city) values ('ON','Brantford');
insert into Travel.destination(province, city) values ('ON','Kanata');
insert into Travel.destination(province, city) values ('ON','Renfrew');
insert into Travel.destination(province, city) values ('ON','Brock');
insert into Travel.destination(province, city) values ('ON','Kincardine');
insert into Travel.destination(province, city) values ('ON','Richmond Hill');
insert into Travel.destination(province, city) values ('ON','Brockville');
insert into Travel.destination(province, city) values ('ON','King');
insert into Travel.destination(province, city) values ('ON','Sarnia');
insert into Travel.destination(province, city) values ('ON','Burlington');
insert into Travel.destination(province, city) values ('ON','Kingston');
insert into Travel.destination(province, city) values ('ON','Sault Ste. Marie');
insert into Travel.destination(province, city) values ('ON','Caledon');
insert into Travel.destination(province, city) values ('ON','Kirkland Lake');
insert into Travel.destination(province, city) values ('ON','Scarborough');
insert into Travel.destination(province, city) values ('ON','Cambridge');
insert into Travel.destination(province, city) values ('ON','Kitchener');
insert into Travel.destination(province, city) values ('ON','Scugog');
insert into Travel.destination(province, city) values ('ON','Chatham-Kent');
insert into Travel.destination(province, city) values ('ON','Larder Lake');
insert into Travel.destination(province, city) values ('ON','Souix Lookout CoC Sioux Lookout');
insert into Travel.destination(province, city) values ('ON','Chesterville');
insert into Travel.destination(province, city) values ('ON','Leamington');
insert into Travel.destination(province, city) values ('ON','Smiths Falls');
insert into Travel.destination(province, city) values ('ON','Clarington');
insert into Travel.destination(province, city) values ('ON','Lennox-Addington');
insert into Travel.destination(province, city) values ('ON','South-West Oxford');
insert into Travel.destination(province, city) values ('ON','Cobourg');
insert into Travel.destination(province, city) values ('ON','Lincoln');
insert into Travel.destination(province, city) values ('ON','St. Catharines');
insert into Travel.destination(province, city) values ('ON','Cochrane');
insert into Travel.destination(province, city) values ('ON','Lindsay');
insert into Travel.destination(province, city) values ('ON','St. Thomas');
insert into Travel.destination(province, city) values ('ON','Collingwood');
insert into Travel.destination(province, city) values ('ON','London');
insert into Travel.destination(province, city) values ('ON','Stoney Creek');
insert into Travel.destination(province, city) values ('ON','Cornwall');
insert into Travel.destination(province, city) values ('ON','Loyalist Township');
insert into Travel.destination(province, city) values ('ON','Stratford');
insert into Travel.destination(province, city) values ('ON','Cumberland');
insert into Travel.destination(province, city) values ('ON','Markham');
insert into Travel.destination(province, city) values ('ON','Sudbury');
insert into Travel.destination(province, city) values ('ON','Deep River');
insert into Travel.destination(province, city) values ('ON','Metro Toronto');
insert into Travel.destination(province, city) values ('ON','Temagami');
insert into Travel.destination(province, city) values ('ON','Dundas');
insert into Travel.destination(province, city) values ('ON','Merrickville');
insert into Travel.destination(province, city) values ('ON','Thorold');
insert into Travel.destination(province, city) values ('ON','Durham');
insert into Travel.destination(province, city) values ('ON','Milton');
insert into Travel.destination(province, city) values ('ON','Thunder Bay');
insert into Travel.destination(province, city) values ('ON','Dymond');
insert into Travel.destination(province, city) values ('ON','Nepean');
insert into Travel.destination(province, city) values ('ON','Tillsonburg');
insert into Travel.destination(province, city) values ('ON','Ear Falls');
insert into Travel.destination(province, city) values ('ON','Newmarket');
insert into Travel.destination(province, city) values ('ON','Timmins');
insert into Travel.destination(province, city) values ('ON','East Gwillimbury');
insert into Travel.destination(province, city) values ('ON','Niagara');
insert into Travel.destination(province, city) values ('ON','Toronto');
insert into Travel.destination(province, city) values ('ON','East Zorra-Tavistock');
insert into Travel.destination(province, city) values ('ON','Niagara Falls');
insert into Travel.destination(province, city) values ('ON','Uxbridge');
insert into Travel.destination(province, city) values ('ON','Elgin');
insert into Travel.destination(province, city) values ('ON','Niagara-on-the-Lake');
insert into Travel.destination(province, city) values ('ON','Vaughan');
insert into Travel.destination(province, city) values ('ON','Elliot Lake');
insert into Travel.destination(province, city) values ('ON','North Bay');
insert into Travel.destination(province, city) values ('ON','Wainfleet');
insert into Travel.destination(province, city) values ('ON','Flamborough');
insert into Travel.destination(province, city) values ('ON','North Dorchester');
insert into Travel.destination(province, city) values ('ON','Wasaga Beach');
insert into Travel.destination(province, city) values ('ON','Fort Erie');
insert into Travel.destination(province, city) values ('ON','North Dumfries');
insert into Travel.destination(province, city) values ('ON','Waterloo');
insert into Travel.destination(province, city) values ('ON','Fort Frances');
insert into Travel.destination(province, city) values ('ON','North York');
insert into Travel.destination(province, city) values ('ON','Waterloo');
insert into Travel.destination(province, city) values ('ON','Gananoque');
insert into Travel.destination(province, city) values ('ON','Norwich');
insert into Travel.destination(province, city) values ('ON','Welland');
insert into Travel.destination(province, city) values ('ON','Georgina');
insert into Travel.destination(province, city) values ('ON','Oakville');
insert into Travel.destination(province, city) values ('ON','Wellesley');
insert into Travel.destination(province, city) values ('ON','Glanbrook');
insert into Travel.destination(province, city) values ('ON','Orangeville');
insert into Travel.destination(province, city) values ('ON','West Carleton');
insert into Travel.destination(province, city) values ('ON','Gloucester');
insert into Travel.destination(province, city) values ('ON','Orillia');
insert into Travel.destination(province, city) values ('ON','West Lincoln');
insert into Travel.destination(province, city) values ('ON','Goulbourn');
insert into Travel.destination(province, city) values ('ON','Osgoode');
insert into Travel.destination(province, city) values ('ON','Whitby');
insert into Travel.destination(province, city) values ('ON','Gravenhurst');
insert into Travel.destination(province, city) values ('ON','Oshawa');
insert into Travel.destination(province, city) values ('ON','Wilmot');
insert into Travel.destination(province, city) values ('ON','Grimsby');
insert into Travel.destination(province, city) values ('ON','Ottawa');
insert into Travel.destination(province, city) values ('ON','Windsor');
insert into Travel.destination(province, city) values ('ON','Guelph');
insert into Travel.destination(province, city) values ('ON','Ottawa-Carleton');
insert into Travel.destination(province, city) values ('ON','Woolwich');
insert into Travel.destination(province, city) values ('ON','Haldimand-Norfork');
insert into Travel.destination(province, city) values ('ON','Owen Sound');
insert into Travel.destination(province, city) values ('ON','York');
insert into Travel.destination(province, city) values ('PE','Alberton');
insert into Travel.destination(province, city) values ('PE','Montague');
insert into Travel.destination(province, city) values ('PE','Stratford');
insert into Travel.destination(province, city) values ('PE','Charlottetown');
insert into Travel.destination(province, city) values ('PE','Souris');
insert into Travel.destination(province, city) values ('PE','Summerside');
insert into Travel.destination(province, city) values ('PE','Cornwall');
insert into Travel.destination(province, city) values ('QC','Alma');
insert into Travel.destination(province, city) values ('QC','Fleurimont');
insert into Travel.destination(province, city) values ('QC','Longueuil');
insert into Travel.destination(province, city) values ('QC','Amos');
insert into Travel.destination(province, city) values ('QC','Gaspe');
insert into Travel.destination(province, city) values ('QC','Marieville');
insert into Travel.destination(province, city) values ('QC','Anjou');
insert into Travel.destination(province, city) values ('QC','Gatineau');
insert into Travel.destination(province, city) values ('QC','Mount Royal');
insert into Travel.destination(province, city) values ('QC','Aylmer');
insert into Travel.destination(province, city) values ('QC','Hull');
insert into Travel.destination(province, city) values ('QC','Montreal');
insert into Travel.destination(province, city) values ('QC','Beauport');
insert into Travel.destination(province, city) values ('QC','Joliette');
insert into Travel.destination(province, city) values ('QC','Montreal Region');
insert into Travel.destination(province, city) values ('QC','Bromptonville');
insert into Travel.destination(province, city) values ('QC','Jonquiere');
insert into Travel.destination(province, city) values ('QC','Montreal-Est');
insert into Travel.destination(province, city) values ('QC','Brosssard');
insert into Travel.destination(province, city) values ('QC','Lachine');
insert into Travel.destination(province, city) values ('QC','Quebec');
insert into Travel.destination(province, city) values ('QC','Chateauguay');
insert into Travel.destination(province, city) values ('QC','Lasalle');
insert into Travel.destination(province, city) values ('QC','Saint-Leonard');
insert into Travel.destination(province, city) values ('QC','Chicoutimi');
insert into Travel.destination(province, city) values ('QC','Laurentides');
insert into Travel.destination(province, city) values ('QC','Sherbrooke');
insert into Travel.destination(province, city) values ('QC','Coaticook');
insert into Travel.destination(province, city) values ('QC','LaSalle');
insert into Travel.destination(province, city) values ('QC','Sorel');
insert into Travel.destination(province, city) values ('QC','Coaticook');
insert into Travel.destination(province, city) values ('QC','Laval');
insert into Travel.destination(province, city) values ('QC','Thetford Mines');
insert into Travel.destination(province, city) values ('QC','Dorval');
insert into Travel.destination(province, city) values ('QC','Lennoxville');
insert into Travel.destination(province, city) values ('QC','Victoriaville');
insert into Travel.destination(province, city) values ('QC','Drummondville');
insert into Travel.destination(province, city) values ('QC','Levis');
insert into Travel.destination(province, city) values ('SK','Avonlea');
insert into Travel.destination(province, city) values ('SK','Melfort');
insert into Travel.destination(province, city) values ('SK','Swift Current');
insert into Travel.destination(province, city) values ('SK','Colonsay');
insert into Travel.destination(province, city) values ('SK','Nipawin');
insert into Travel.destination(province, city) values ('SK','Tisdale');
insert into Travel.destination(province, city) values ('SK','Craik');
insert into Travel.destination(province, city) values ('SK','Prince Albert');
insert into Travel.destination(province, city) values ('SK','Unity');
insert into Travel.destination(province, city) values ('SK','Creighton');
insert into Travel.destination(province, city) values ('SK','Regina');
insert into Travel.destination(province, city) values ('SK','Weyburn');
insert into Travel.destination(province, city) values ('SK','Eastend');
insert into Travel.destination(province, city) values ('SK','Saskatoon');
insert into Travel.destination(province, city) values ('SK','Wynyard');
insert into Travel.destination(province, city) values ('SK','Esterhazy');
insert into Travel.destination(province, city) values ('SK','Shell Lake');
insert into Travel.destination(province, city) values ('SK','Yorkton');
insert into Travel.destination(province, city) values ('SK','Gravelbourg');
insert into Travel.destination(province, city) values ('YT','Carcross');
insert into Travel.destination(province, city) values ('YT','Whitehorse');
insert into Travel.destination(province, city) values ('YT','Dawson');
insert into Travel.destination(province, city) values ('YT','Faro');
insert into Travel.destination(province, city) values ('YT','Haines Junction');
insert into Travel.destination(province, city) values ('YT','Mayo');
insert into Travel.destination(province, city) values ('YT','Teslin');
insert into Travel.destination(province, city) values ('YT','Watson Lake');
insert into Travel.destination(province, city) values ('YT','Old Crow');
insert into Travel.destination(province, city) values ('YT','Otter Falls');
insert into Travel.destination(province, city) values ('YT','Ealge Plains');
insert into Travel.destination(province, city) values ('YT','Salmon Arm');

--BUILD LOOKUP TABLES
Create Table Travel.PurposeLookup(
PurposeLUpID smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
purposetype varchar (100),
CreateDate date,
CreateUser varchar (10),
ModDate date,
ModUser varchar(10)
);

create table Travel.PoolCarLookup(
PoolCarLUPID  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
PoolCarType varchar (50) not null,
PoolCarCost smallint not null,
CreateDate date,
CreateUser varchar (10),
ModDate date,
ModUser varchar(10)
);

create table Travel.RentalCarLookup(
RentalCarLUPID  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
RentalCarType varchar (50) not null,
RentalCarCost smallint not null,
CreateDate date,
CreateUser varchar (10),
ModDate date,
ModUser varchar(10)
);

create table Travel.FlightEstimateLookup(
FlightEstimLUPID  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
Destination varchar (140) not null,
RoundCost smallint not null,
CreateDate date,
CreateUser varchar (10),
ModDate date,
ModUser varchar(10)
);


--BUILD PRIMARY TABLES
Create Table Travel.Purpose(
pid  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
taid smallint not null,
PurposeLUPID smallint not null, --fk
detail varchar(140),
name varchar(60),
URl varchar(150),
location varchar(100),
FOREIGN KEY (PurposeLUPID) REFERENCES Travel.PurposeLookup(PurposeLUPID)
);

create Table Travel.PreApprove(
preappID smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
deptid varchar(8) not null,
name varchar(140),
purposelupid smallint not null, --FK
purposedesc varchar(140),
cost smallint,
traveldate date,
FOREIGN KEY (purposelupid) REFERENCES Travel.PurposeLookup(PurposeLUPID)
);

create table Travel.PreAppEmployee(
preappempID  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
preappid smallint not null, --FK
employeeynet varchar(8),
FOREIGN KEY (preappid) REFERENCES Travel.Preapprove(preappid)
);

create table Travel.PreAppDoc(
	preappdocID  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	preappid smallint not null, --FK
	document bytea,
	FOREIGN KEY (preappid) REFERENCES Travel.Preapprove(preappid)
);

create table Travel.Auth(
	TAId smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	UserId smallint not null, --fk
	FirstName varchar (50), --autocompete using Directory API
	LastName varchar (50),
	Department varchar (100), --maybe there is an api we can use
	Division varchar(100),
	Branch varchar (100), -- maybe there is an api we can use
	Unit varchar (100),
	Email varchar (100),
	Mailcode varchar(10),
	DaysNotTravel smallint,
	DateBackToWork date,
	TravelDuration smallint,
	Purpose varchar(100),
	TravelAdvance integer,
	EventName varchar(100),
	Summary varchar(1000),
	FormStatus varchar(25) not null,
	FormId varchar(50),
	SupervisorEmail varchar(100),
	PreappId smallint,
	Approved varchar(50),
	FOREIGN KEY (preappid) REFERENCES Travel.Preapprove(preappid)
);

create table Travel.Expenses(
	id smallint GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint,
	name varchar(100),
	type varchar(100),
	cost numeric,
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)

	
);

create table Travel.Stops(
	id smallint GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint, --fk
	travelFrom varchar(100),
	travelTo varchar(100),
	departureDate date, 
	departureTime time,
	transport varchar(100),
	estimate smallint,
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

create table Travel.FlightRequest(
	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint not null, --fk
	DOB date not null,
	LegalFirstName varchar(100) not null,
	LegalLastName varchar(100) not null,
	TravellorPhone varchar (25) not null,
	TravellorEmail varchar (50) not null,
	PrefDeptDate date,
	PrefDeptTime varchar (2), --am or pm
	PrefReturnDate date,
	PrefReturnTime varchar(2), --am or pm
	TravelNotes varchar(200),
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

create table Travel.Approve(
	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint not null, -- fk
	status varchar (20),
	approverID varchar(10), --ynet name
	approveDate date,
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

create table Travel.Carryout(
	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint, --fk
	type varchar(15),
	otherdesc varchar (140),
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

create table Travel.CostEstimate(
	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint, --fk
	expensetype varchar(15),
	expensedesc varchar(100),
	quantity smallint,
	amount smallint,
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

create table Travel.Advance(
	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint, --fk
	amount smallint,
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

create Table Travel.Expense(
	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint, --fk
	expensetype varchar(15),
	expensedesc varchar(100),
	quantity smallint,
	amount smallint,
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

create table Travel.RecieptBackup(
    id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
    expenseid smallint not null, --fk
    document bytea,
	FOREIGN KEY (expenseID) REFERENCES Travel.Expense(id)
);

create table Travel.Docs (
	id  smallint not null GENERATED BY DEFAULT AS IDENTITY primary key,
	taid smallint, --fk
	document bytea,
	FOREIGN KEY (taid) REFERENCES Travel.Auth(taid)
);

ALTER TABLE travel.auth
DROP constraint auth_preappid_fkey;